# globals for application run on Windows

WINDOW_WIDTH = 1050
WINDOW_HEIGHT = 550

FIELD_WITH_PARAMETERS_WIDTH = 250
FIELD_WITH_PARAMETERS_HEIGHT = 300
FIELD_WITH_PARAMETERS_BUTTON_PADY = 5
FIELD_WITH_PARAMETERS_SPINBOX_WIDTH = 16
FIELD_WITH_PARAMETERS_LABEL_WIDTH = 15

WORKING_AREA_SIZE = 550

CANVAS_SIZE = 500

GRAPH_FRAME_WIDTH = 250
GRAPH_FRAME_HEIGHT = 500

RULER_WIDTH = 500
RULER_HEIGHT = 30

RULER_BOTTOM_FILE = "img/ruler_d_mac.png"
RULER_LEFT_FILE = "img/ruler_l_mac.png"
RULER_GRAPH_FILE = "img/ruler_graph.png"
